import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from '@/app/components/TopHeader/TopHeader';
import Footer from '@/app/components/Footer/Footer';
import "@/app/styles/global.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
