import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/app/styles/global.css";

import Footer from '@/app/components/Footer/Footer';
import Header from '@/app/components/TopHeader/TopHeader';
import StickyHeader from "@/app/components/StickyHeader/StickyHeader";
import Sidebar from "@/app/components/Sidebar/Sidebar";
import ProgressBar from "@/app/components/ProgressBar/ProgressBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <div>
          <StickyHeader />
          <main className='main container'>
            <div className='layoutRow'>
              <aside className='sidebar'>
                <Sidebar />
              </aside>
              {children}
            </div>
          </main>
          <ProgressBar />
          <Footer />
        </div>
      </body>
    </html>
  );
}
